
export const GET_RECIPE_BY_KEYWORD = "GET_RECIPE_BY_KEYWORD";
export const LOADING_ON = "LOADING_ON";
export const LOADING_OFF = "LOADING_OFF";
export const NO_RECIPES_FOUND = "NO_RECIPES_FOUND";
export const RESET_NOTIFICATIONS = "RESET_NOTIFICATIONS";